stages:
  prepare:
    cmd: python -m src.data.make_dataset
    deps:
      - src/data/make_dataset.py
      - data/raw/UCI_Credit_Card.csv
    params:
      - data
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  
  features:
    cmd: python -m src.features.build_features
    deps:
      - src/features/build_features.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - features
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv
  
  train:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - src/models/pipeline.py
      - data/processed/train_features.csv
      - data/processed/test_features.csv
    params:
      - model
      - training
      - mlflow
    outs:
      - models/model.pkl
    metrics:
      - models/metrics.json:
          cache: false