# ============================================================
# DVC Pipeline — end-to-end ML workflow for Credit Scoring PD-model
# ============================================================

stages:

  # ----------------------------------------------------------
  # 1️⃣ PREPARE — загрузка и очистка сырых данных
  # ----------------------------------------------------------
  prepare:
    cmd: python -m src.data.make_dataset
    deps:
      - src/data/make_dataset.py
      - data/raw/UCI_Credit_Card.csv
      - params.yaml
    params:
      - data
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  # ----------------------------------------------------------
  # 2️⃣ FEATURES — инженерия признаков
  # ----------------------------------------------------------
  features:
    cmd: python -m src.features.build_features
    deps:
      - src/features/build_features.py
      - data/processed/train.csv
      - data/processed/test.csv
      - params.yaml
    params:
      - features
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv

  # ----------------------------------------------------------
  # 3️⃣ TRAIN — обучение модели и логирование в MLflow
  # ----------------------------------------------------------
  train:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - src/models/pipeline.py
      - data/processed/train_features.csv
      - data/processed/test_features.csv
      - params.yaml
    params:
      - model
      - training
      - mlflow
    outs:
      - models/model.pkl
    metrics:
      - models/metrics.json:
          cache: false

  # ----------------------------------------------------------
  # 4️⃣ DRIFT — контроль дрифта данных (Population Stability Index)
  # ----------------------------------------------------------
  drift:
    cmd: python -m src.monitoring.drift
    deps:
      - src/monitoring/drift.py
      - data/processed/train_features.csv
      - data/processed/test_features.csv
      - models/model.pkl
      - params.yaml
    params:
      - monitoring
    outs:
      - models/drift_report.json

