data:
  raw_path: data/raw/UCI_Credit_Card.csv
  processed_path: data/processed/
  train_raw_path: data/processed/train.csv
  test_raw_path: data/processed/test.csv
  train_features_path: data/processed/train_features.csv
  test_features_path: data/processed/test_features.csv
  test_size: 0.2
  random_state: 42
  target: target
features:
  age_bins:
  - 18
  - 30
  - 45
  - 60
  - 100
  age_labels:
  - young
  - middle
  - senior
  - elderly
model:
  algorithm: gradient_boosting
  random_state: 42
  logistic_regression:
    penalty: l2
    C: 1.0
    max_iter: 1000
    solver: lbfgs
    class_weight: balanced
  random_forest:
    n_estimators: 50
    max_depth: 10
    min_samples_split: 20
    min_samples_leaf: 10
    class_weight: balanced
    random_state: 42
  gradient_boosting:
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 5
    min_samples_split: 20
    min_samples_leaf: 10
    random_state: 42
training:
  cv_folds: 3
  scoring: roc_auc
mlflow:
  tracking_uri: ./mlruns
  experiment_name: credit_scoring
monitoring:
  psi_threshold: 0.25
  buckets: 10
  features_to_monitor:
  - utilization_last
  - pay_delay_sum
  - pay_delay_max
  - bill_trend
  - pay_trend
  - bill_avg
  - pay_amt_avg
  - pay_to_bill_ratio
