# ===========================
# DATA CONFIGURATION
# ===========================
data:
  raw_path: data/raw/UCI_Credit_Card.csv   # сырой датасет (DVC)
  processed_path: data/processed/          # директория для промежуточных артефактов

  # Выходы стадии PREPARE (очищенные данные, без признаков)
  train_raw_path: data/processed/train.csv
  test_raw_path:  data/processed/test.csv

  # Выходы стадии FEATURES (данные с инженерными признаками)
  train_features_path: data/processed/train_features.csv
  test_features_path:  data/processed/test_features.csv

  test_size: 0.2                     # доля тестовой выборки
  random_state: 42                   # фиксируем рандом
  target: target                     # имя столбца целевой переменной


# ===========================
# FEATURE ENGINEERING
# ===========================
features:
  # категории возраста (для age_bin)
  age_bins: [18, 30, 45, 60, 100]
  age_labels: ['young', 'middle', 'senior', 'elderly']


# ===========================
# MODEL SETTINGS
# ===========================
model:
  algorithm: gradient_boosting    # текущая модель (выбор)
  random_state: 42                # фиксация семени

  # Параметры для GridSearchCV
  logistic_regression:
    penalty: l2
    C: 1.0
    max_iter: 1000
    solver: lbfgs
    class_weight: balanced

  random_forest:
    n_estimators: 50
    max_depth: 10
    min_samples_split: 20
    min_samples_leaf: 10
    class_weight: balanced
    random_state: 42

  gradient_boosting:
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 5
    min_samples_split: 20
    min_samples_leaf: 10
    random_state: 42


# ===========================
# TRAINING CONFIG
# ===========================
training:
  cv_folds: 3                 # количество фолдов
  scoring: roc_auc            # метрика



# ===========================
# MLFLOW TRACKING
# ===========================
mlflow:
  tracking_uri: ./mlruns      # локальный backend для экспериментов
  experiment_name: credit_scoring



# ===========================
# MONITORING CONFIG
# ===========================
monitoring:
  psi_threshold: 0.25         # порог значимого дрифта
  buckets: 10                 # количество бинов PSI
  features_to_monitor:
    - utilization_last
    - pay_delay_sum
    - pay_delay_max
    - bill_trend
    - pay_trend
    - bill_avg
    - pay_amt_avg
    - pay_to_bill_ratio
