name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DVC pipeline
      run: dvc repro --force

    - name: Run pytest
      run: pytest -q
name: ML Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-ci:
    name: Run DVC + Tests
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Устанавливаем зависимости системы
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    # 4️⃣ Устанавливаем зависимости проекта
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc dvc-gdrive

    # 5️⃣ Вытягиваем данные (если DVC подключен)
    - name: Pull DVC data
      run: |
        dvc pull || echo "DVC data not configured — skipping 👍"

    # 6️⃣ Запускаем весь pipeline
    - name: Run DVC pipeline
      run: |
        dvc repro --force

    # 7️⃣ Запускаем тесты
    - name: Run tests
      run: |
        pytest -q --disable-warnings --maxfail=1

